apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
  name: {{ .Values.pv.name }}
spec:
  capacity:
    storage: {{ .Values.pv.spec.capacity.storage }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: {{ .Values.hostName }}-volumeHandle # make sure this volumeid is unique for every identical share in the cluster
    volumeAttributes:
      resourceGroup: {{ .Values.resourceGroupName }} # resourceGroupName where storage is present
      shareName: {{ .Values.fileShareName }} #file share name that we created in azure storage
    nodeStageSecretRef:
      name: {{ .Values.secret.name }} # secret of azure storage we created
      namespace: {{ .Release.Namespace }}
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict
    - nosharesock
    - nobrl