apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-{{ .Values.addins.hostName }}-addins-taskweb-dep
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.addins.hostName }}-addins-taskweb-dep
  minReplicas: {{ .Values.addins.hpa.minReplicas }}
  maxReplicas: {{ .Values.addins.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.addins.hpa.resource.cpu.averageUtilization }} # suggested defaultValue:  70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.addins.hpa.resource.memory.averageUtilization }}  # suggested defaultValue:  98
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.addins.hpa.behavior.scaleDown.stabilizationWindowSeconds }}  # suggested defaultValue:  120
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.addins.hpa.behavior.scaleUp.stabilizationWindowSeconds }}  # suggested defaultValue:  120