apiVersion: apps/v1
kind: Deployment
metadata:
  name: mount-secret-ingress-deployment
spec:
  replicas: 1 # Number of desired replicas
  selector:
    matchLabels:
      app: mount-secret-ingress
  template:
    metadata:
      labels:
        app: mount-secret-ingress
    spec:
      automountServiceAccountToken: false 
      containers:
      - name: my-container
        image: ubuntu:latest # Use the latest Ubuntu image
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true            
        command: ["/bin/sleep", "infinity"] # Keep the container running
        resources:
          limits:
            cpu: 400m
            memory: 512M
          requests:
            cpu: 200m
            memory: 256M
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      nodeSelector:
        "kubernetes.io/os": linux
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-tls"