apiVersion: batch/v1
kind: Job
metadata:
  name: pre-install
  annotations:
    "helm.sh/hook": pre-install
spec:
  template:
    spec:
      containers:
      - name: pre-install
        image: icmlcr.azurecr.io/runners/windows-upgrade:35
        command: ["powershell" "start-sleep" "21"]
      restartPolicy: OnFailure