apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-tls
spec:
  provider: azure
  secretObjects:                            # secretObjects defines the desired state of synced K8s secret objects
    - secretName: ingress-tls-csi
      type: kubernetes.io/tls
      data: 
        - objectName: {{ .Values.secretProvider.sslCertName }}
          key: tls.key
        - objectName: {{ .Values.secretProvider.sslCertName }}
          key: tls.crt
    - secretName: ingress-ici-user-content-secret
      type: kubernetes.io/tls
      data: 
        - objectName:  {{ .Values.secretProvider.usercontentSslCertName }}
          key: tls.key
        - objectName: {{ .Values.secretProvider.usercontentSslCertName }}
          key: tls.crt
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.secretProvider.sslManagedClientId }}
    keyvaultName: {{ .Values.secretProvider.sslAkvName }}               # the name of the AKV instance
    objects: |
      array:
        - |
          objectName: {{ .Values.secretProvider.sslCertName }}
          objectType: secret
        - |
          objectName: {{ .Values.secretProvider.usercontentSslCertName }}
          objectType: secret
    tenantId: {{ .Values.secretProvider.sslAkvTenantId }}                    # the Subscription ID of the AKV instance